Set Golang to the 1.21.7 stable version
Workflows failed on CI.

I noticed the following error messages:

> go: errors parsing go.mod:
> Error: /home/runner/work/gobl.xinvoice/gobl.xinvoice/go.mod:3:
> invalid go version '1.21.6': must match format 1.23
> Error: Process completed with exit code 1.

> Running [/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint
> run --out-format=github-actions] in [] ...
> level=error msg="Running error: context loading failed:
> failed to load packages: failed to load with go/packages:
> err: exit status 1: stderr: go: errors parsing go.mod:\n
> /home/runner/work/gobl.xinvoice/gobl.xinvoice/go.mod:3:
> invalid go version '1.21.6': must match format 1.23\n"
>
> Error: golangci-lint exit with code 3

I looked at what versions of Go are installed and it turned out
that there were no consequences.

The latest stable version of Go is 1.22. [1]

@samlown said:
> 1.22 is a bit too new still for most people to have caught up.

So we decide to use at most 1.21 version.

[1]: https://go.dev/dl/